name: "tagged-release"

on:
  push:
    tags:
      - "*.*"

jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@fix_action_retval
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref }}"
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    steps:

      # --- from gradle.yml ---
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build check
      # --- from gradle.yml ---

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*all.jar
